### ISSUE TITLE
Different application's name present in login/signup page

### ISSUE THREAD

**Issue by SujanNeupane42** [prajwalad101/aims#11]
@Prajwalad101 This is a high severance issue. While logging in or signing up into AIMS, the system prompts that the user is logging/signing into
![wrong_application_name](https://user-images.githubusercontent.com/85225585/166184271-ab53cd62-4c11-4d9e-afde-997ac9768ec3.PNG)
 a software named "**BugEngine**" when our software's name is **Agriculture Information Management System**.

@Prajwalad101  Please solve this issue ASAP !!

**Comment by prajwalad101** [comment]
The issue persists because the application was accidentally registered as a different application. I have created a new application on Google API Console. Now the correct application name shows on the sign up screen.

![AIMS](https://user-images.githubusercontent.com/84787320/166184560-f7850dd7-0635-499c-953a-f2aa36ba46ef.PNG)
